/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b3137a1d-79d6-4f48-859b-af672311f760",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_mQpy9cuyE",
    "aws_user_pools_web_client_id": "6hsalmg5aevdrhjukqjj8su3e9",
    "oauth": {
        "domain": "kompetansekartleggine8062390-e8062390-migrate.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://googlelogin.d26o3uvnva5774.amplifyapp.com/,http://localhost:3000/,https://master.d26o3uvnva5774.amplifyapp.com/,https://dev.d26o3uvnva5774.amplifyapp.com/,https://testback.d26o3uvnva5774.amplifyapp.com/,https://dev.kompetanse.knowit.no/",
        "redirectSignOut": "https://googlelogin.d26o3uvnva5774.amplifyapp.com/,http://localhost:3000/,https://master.d26o3uvnva5774.amplifyapp.com/,https://dev.d26o3uvnva5774.amplifyapp.com/,https://testback.d26o3uvnva5774.amplifyapp.com/,https://dev.kompetanse.knowit.no/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [],
    "aws_appsync_graphqlEndpoint": "https://2onjfurhgrezhowdkhnguqxlwe.appsync-api.eu-central-1.amazonaws.com/graphql",//"https://wfy4iwfxebg6dlzs5u7zjbh364.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "externalAPI",
            "endpoint": "https://65iwvl3jha.execute-api.eu-central-1.amazonaws.com/migrate",
            "region": "eu-central-1"
        },
        {
            "name": "AdminQueries",
            "endpoint": "https://yaha0dw3s2.execute-api.eu-central-1.amazonaws.com/migrate",
            "region": "eu-central-1"
        }
    ],
    "aws_mobile_analytics_app_id": "0554ea4a12064cc18d224c0f404fd456",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
