const ORGANIZATION_ID_ATTRIBUTE = 'custom:OrganizationID'
const ADMIN_COGNITOGROUP_SUFFIX = '0admin'
const GROUPLEADER_COGNITOGROUP_SUFFIX = '0groupLeader'
const SUPER_ADMIN_COGNITO_GROUP = 'admin'

export {
  ORGANIZATION_ID_ATTRIBUTE,
  ADMIN_COGNITOGROUP_SUFFIX,
  GROUPLEADER_COGNITOGROUP_SUFFIX,
  SUPER_ADMIN_COGNITO_GROUP,
}
