/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:a3821dea-78f6-4c05-98b6-42479a8bf446",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_QBzfE9Xza",
    "aws_user_pools_web_client_id": "4ub27tr6dbvneiml0qbmiuj75l",
    "oauth": {
        "domain": "kompetansekartleggine8062390-e8062390-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://googlelogin.d26o3uvnva5774.amplifyapp.com/,http://localhost:3000/,https://master.d26o3uvnva5774.amplifyapp.com/,https://dev.d26o3uvnva5774.amplifyapp.com/,https://testback.d26o3uvnva5774.amplifyapp.com/,https://dev.kompetanse.knowit.no/",
        "redirectSignOut": "https://googlelogin.d26o3uvnva5774.amplifyapp.com/,http://localhost:3000/,https://master.d26o3uvnva5774.amplifyapp.com/,https://dev.d26o3uvnva5774.amplifyapp.com/,https://testback.d26o3uvnva5774.amplifyapp.com/,https://dev.kompetanse.knowit.no/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "USERNAME"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [],
    "aws_appsync_graphqlEndpoint": "https://sgclonuhk5ffnfqpqmn55ogtq4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-imbt7s2xcfadxo6n7sgxtksqna",
    "aws_cloud_logic_custom": [
        {
            "name": "externalAPI",
            "endpoint": "https://vzspmckcea.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        },
        {
            "name": "AdminQueries",
            "endpoint": "https://oz71fwpwg0.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ],
    "aws_content_delivery_bucket": "kompetansekartleggin-20220218135538-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://kompetansekartleggin-20220218135538-hostingbucket-dev.s3-website.eu-central-1.amazonaws.com"
};


export default awsmobile;
